### ISSUE TITLE
Update save once?

### ISSUE THREAD

**Issue by Moon-developer** [74oshua/BetterTerrain#1]
HI

Not sure I fully follow how this mod works, but after it creates the new hmap can I remove the mod and let the game use that hmap going forward? I ask because my friend levelled an entire area and I was wondering if creating a new hmap once off will help with the lag in the area from all the Terrain modifications.

[after backing up the world that is incase of mishaps.]

**Comment by 74oshua** [comment]
The .hmap file is useless without the mod. The TerrainModifiers are still spawned without the mod, and you won't get any difference in performance without the mod.

**Comment by Moon-developer** [comment]
I see, that makes sense. Good job on working on this tool by the way. I can see this would be quite a challenging fix without reworking the whole game code base.
